ktor:
  application:
    modules:
      - com.application.ApplicationKt.module
  deployment:
    port: ${PORT:8080}
    host: "0.0.0.0"
  database:
    url: "jdbc:postgresql://localhost:5432/todapp"
    driver: "org.postgresql.Driver"
    user: "postgres"
    password: "postgrespw"
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
telegram:
  botToken: ${TG_BOT_TOKEN}
  botUsername: ${TG_BOT_USERNAME}